title: The Stories of A.Andiron
description: Weird erotica for when you need monsters, heavy metal sex, and tortured metaphors in your bedroom.
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
