title: The Stories of A.Andiron
description: Weird erotica for when you need monsters, heavy metal sex, and tortured metaphors in your bedroom.
show_downloads: false
google_analytics: UA-241182265-3
theme: jekyll-theme-tactile
