title: The Stories of A.Andiron
description: Weird erotica for when you need monsters, heavy metal sex, and tortured metaphors in your bedroom.
show_downloads: false
  # google_analytics: UA-241432430-1
google_analytics: G-EEX5TGZ7GT
theme: jekyll-theme-tactile
